#pragma config(Sensor, dgtl1,  Forward,        sensorTouch)
#pragma config(Sensor, dgtl2,  BackWard,       sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int ramp = 0;
	int spd = 0;
while(true) {

if(SensorValue(BackWard) == 1) {
	if(ramp == 0) {
	spd = -30;
	ramp = 10;
}
else if(ramp <= 10) {
	spd = -50;
	ramp = ramp+1;
}
else if(ramp <= 20) {
	spd = -70;
	ramp = ramp+1;
}
else if(ramp <= 30) {
	spd = -100;
	ramp = ramp+1;
}
else if(ramp >= 40) {
	spd = -120;
	ramp = ramp+1;
}

}
else {
		if(ramp >= 40) {
	spd = -100;
	ramp = ramp-1;
}
else if(ramp >= 30) {
	spd = -80;
	ramp = ramp-1;
}
else if(ramp >= 20) {
	spd = -60;
	ramp = ramp-1;
}
else if(ramp >= 10) {
	spd = -40;
	ramp = ramp-1;
}
else if(ramp >= 0) {
	spd = 0;
	ramp = 0;
}
}

	motor[port1] = -60;
		motor[port2] = spd;
		motor[port3] = spd;
		motor[port4] = spd;
		motor[port5] = spd;
		motor[port6] = -spd;
		motor[port7] = -spd;
		motor[port8] = -spd;
		motor[port9] = -spd;
		motor[port10] = -spd;
		wait1Msec(200);
}


}
